### ISSUE TITLE
PR #1 Causes issues if multiple spell files are set

### ISSUE THREAD

**Issue by ErebusBat** [micarmst/vim-spellsync#2]
I just updated and ran into an issue caused by #1.

I use multiple `spellfile`s, looking something like:

```
set spellfile+=~/.config/nvim/spell/en.utf-8.add
set spellfile+=~/.config/nvim/spell/work.utf-8.add
set spellfile+=~/.config/nvim/spell/personal.utf-8.add
```

This keeps things separated (i.e. people's unique names, or work project names).  However with the change from #1 this causes an issue because `spellfile` is then defined as: `spellfile=~/.config/nvim/spell/en.utf-8.add,~/.config/nvim/spell/tractionguest.utf-8.add,~/.config/nvim/spell/personal.utf-8.add` which causes issues when trying to parse the path.

I have reverted in my local copy #1 and that resolved the issue.  However I would love it if I could keep in line with uptstream (even if it does take me 5 months up update 😅 ).

I see two immediate options for a resolution:
1. Don't use the new logic from #1 if `spellfile` has a comma in it
2. Split on commas and use the path from the first item for the logic in #1

**Comment by micarmst** [comment]
Hi @ErebusBat, thank you for the detailed write up on this issue and your proposed solutions. I'm leaning towards your second idea of splitting on the comma and using the first item. I will take a closer look at this soon as I'm waiting for my new laptop to arrive but it might take a few weeks.

@Gavin-Paolucci-Kleinow do you have any thoughts on this and do you think option 2 will work OK with your PR?
